### PR TITLE
Put #ifdef around all Serial.printf calls. Sometimes Serial does not exist

### PR DESCRIPTION
**Pull request by phdussud**
Hi Kurt, 
I am using your library in a context where Serial isn't defined because of my USB configuration. 
I am looking forward to your comments. 
Thanks, 
Patrick.

### CODE REVIEW

**Comment by KurtE** [comment]
Looks reasonable.  Normally might be nice to add the defines for debug in either the header file or .cpp file and have them maybe commented out.

Also a tradeoff, wth some of these types of messages as they maybe give some one more hints about why something is not working.

**Comment by phdussud** [comment]
Please note that the defines I used are not new. They were present and used in all of the .cpp files that I changed. 
I believe they are already defined and commented out in their relevant .cpp files. 
Thanks, 
Patrick

**Comment by KurtE** [comment]
Thanks, 

I debated with myself, as there are sort of two levels of debug.  The first sort of the internal. which was under the debug, and these which are the ones to let you know something failed.  

But I understand in your case where Serial does not exist.   

So went ahead and merged.

**Comment by phdussud** [comment]
Thank you. I understand. I would suggest that the best way to communicate what went wrong is with the return value. Right now it is a bool but if it were an enum you could return the exact reason and the calling code would be able to reason about the reason and take appropriate action. What do you think? 
Best, 
Patrick

**Comment by KurtE** [comment]
Yes I understand exactly what you are saying… Probably should do it.  But I also know from experience that almost no one actually looks at the return values.  So again hard to say … 

But I went ahead and merged and will see if someone complains later…

**Pull request merged**
